### ISSUE TITLE
能支持最新的agora_python_server_sdk吗

### ISSUE THREAD

**Issue by yinyajun** [AgoraIO/agora-realtime-ai-api#2]
如果不设置agora_parameter.set_parameters("{\"rtc.audio.enable_user_silence_packet\":true}")，那么用户刚说完话客户端静音的话，将会不产生audio frame包，这样realtime接口的vad将不会激活，导致程序僵住。

低版本的agora_python_server_sdk不支持这么设置

**Comment by weihongqin163** [comment]
这个是rtc sdk所支持的功能。从python 2.1.0之后，才开始支持这个功能

**Comment by plutoless** [comment]
@yinyajun we've updated the version to 2.1.7
